apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

resources:
  - ../../base
  - scc-rolebinding-hostnetwork.yaml

patches:
  - path: patches/route-host.yaml
  - path: patches/deployment-tz.yaml  
  - path: patches/host-network.yaml
