apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

labels:
  - pairs:
      app.kubernetes.io/part-of: home-assistant
      app.kubernetes.io/managed-by: argocd
    includeSelectors: true

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - scc-rolebinding.yaml
  - pvc.yaml
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
